services:
  hikyo:
    build: .
    container_name: hoge-hikyo
    volumes:
      - ./:/src
    tty: true
    ports:
      - 5000:5000
    expose:
      - 5000
    command: pipenv run python webif.py
