python make_input_faculty_main_1.py elementary_school
pypy3 make_input_faculty_main_2.py elementary_school

python make_input_faculty_main_1.py post_office
pypy3 make_input_faculty_main_2.py post_office